# Generated by Django 4.1.5 on 2023-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
